### ISSUE TITLE
"dsntk is excessively stringent"

### ISSUE THREAD

**Issue by DaanJG** [DecisionToolkit/dsntk#8]
Hi!

I've made a simple DMN model in the modeler of Camunda 8 and parsing it with dsntk (or dmntk) gives an error:

```
$ dsntk pdm test.dmn
parsing model file failed with reason: <ModelParserError> expected mandatory child node 'variable' in parent node 'inputData' at [32:3]
```

I actually get this error for any model build in Camunda's modeler. (I do not get the error with models build in Trisotech's modeler or KIE's modeler associated with drools.) Manually adding the 'variable' node to the xml fixed the error and fixing a similar error results in file that can be parsed and evaluated by dsntk, but the output still a bit weird:

```
$ dsntk edm -i Positive test.json test_fixed.dmn
"null(context has no value for key 'False')"
```

I have contacted Camunda support about the issue and their response is:

> Our engineers examined both the DMN 1.3 specification and the XML schema (XSD) for that specification.
> According to the schema, the variable child node is not mandatory on Input Data elements based on minOccurs="0" value:
> 
> ```
> <xsd:element name="inputData" type="tInputData" substitutionGroup="drgElement"/>
>     <xsd:complexType name="tInputData">
>         <xsd:complexContent>
>             <xsd:extension base="tDRGElement">
>                 <xsd:sequence>
>                     <xsd:element name="variable" type="tInformationItem" minOccurs="0"/>
>                 </xsd:sequence>
>             </xsd:extension>
>         </xsd:complexContent>
>     </xsd:complexType>
> ```
> In the context of Camunda DMN modeling solutions, the variable is not included.
> 
> In our view, dmntk is excessively stringent, requiring more than what is strictly necessary according to the DMN specification.
> If you intend to use dmntk as your DMN engine, you can preprocess the DMN models generated in Camunda tools by adding the variable element where it is necessary. This can be accomplished via a simple XSLT script.

My main reason to post this issues to help the developers of dsntk and its users. Although a solution would be helpful for me, it's not very urgent.

I have attached the files with altered file extensions or github wouldn't let me.

[test.json](https://github.com/dsntk/dsntk-rs/files/13392623/test.json)
[test.txt](https://github.com/dsntk/dsntk-rs/files/13392624/test.txt)
[test_fixed.txt](https://github.com/dsntk/dsntk-rs/files/13392625/test_fixed.txt)

**Comment by ghost** [comment]
Hi @DaanJG, thanks for trying **Decision Toolkit** and for this question!

Yes, **dsntk** is stringent, exactly as mentioned in the title and by colleagues from Camunda ;-) when it comes to the **variable** definitions.

Although it is not required by DMN specification (also by the newest), it is a good DMN practice to place variable definitions in the model, to precisely define the variable attributes (like **type**) and use it as described in specification. All DMN models used in [compatibility tests](https://github.com/dmn-tck/tck) define these variables.

**Decision Toolkit** uses variable definitions extensively to precisely manage type conversions and few other things. I can only suspect why this variable element is not mandatory in DMN specification, but I am not a part of this process, so I could be wrong.

Anyway, **dsntk** requires this variable definition and it is not against DMN specification. Simply speaking, models that do not have these variable definitions are correct from DMN specification point of view, but are not usable in **dsntk**. I am not sure if other DMN engines work properly without those variable definitions, or they just "add" them under the hood with default names and types.

But the clue of this post is to get things working I guess ;-), so there is a fixed DMN model shown below, prepared based on your example.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<definitions namespace="https://dsntk.io/example"
             id="_example"
             name="Simple decision table"
             xmlns="https://www.omg.org/spec/DMN/20191111/MODEL/">

  <decision name="Positive">
    <variable typeRef="boolean" name="output"/>

    <informationRequirement>
      <requiredInput href="#_input_data" />
    </informationRequirement>

    <decisionTable hitPolicy="FIRST">
      <input label="x">
        <inputExpression typeRef="number">
          <text>x</text>
        </inputExpression>
      </input>
      <output label="Positive" name="Positive" typeRef="boolean" />
      <rule>
        <inputEntry>
          <text>&gt;0</text>
        </inputEntry>
        <outputEntry>
          <text>true</text>
        </outputEntry>
      </rule>
      <rule>
        <inputEntry>
          <text>-</text>
        </inputEntry>
        <outputEntry>
          <text>false</text>
        </outputEntry>
      </rule>
    </decisionTable>
  </decision>

  <inputData name="x" id="_input_data">
    <variable name="x" typeRef="number"/>
  </inputData>

</definitions>
```
I have removed a lot of noisy attributes to make this model simpler to read.
There are four changes made in your original model to make it work properly:
1. Added `<variable name="x" typeRef="number"/>` in input data.
2. Added `<variable typeRef="boolean" name="output"/>` in the decision.
3. Changed `False` in decision table to **false**.
4. Changed `True` in decision table to **true**.

Points 1 and 2 are variables to define precisely the type and name of input data of the decision and output data returned by the decision. Points 3 and 4 are proper definitions of boolean literals used in FEEL. The error `null(context has no value for key 'False')` was reported by **dsntk** because `False` may be a correct variable name in FEEL. Boolean literals are **true** and **false** in FEEL.

Assuming that the file `test.dmn` contains a model shown above, and the file `test.json` contains `{"x": 0.1}`, run:
```
$ dsntk edm -i Positive test.json test.dmn
true
```
Changing `test.json` content to `{"x": -0.1}` will give:
```
$ dsntk edm -i Positive test.json test.dmn
false
```
Summarizing, it is a hard way to get the proper DMN model out from visual tools, especially because the DMN specification allows for some differences that are differrently interpreted by each visual tool. The best way to get a feeling how proper DMN models (from practical point of view) should look like, is to take a look at [Technology Compatibility Kit for the Decision Model and Notation (DMN) standard](https://github.com/dmn-tck/tck) mentioned above. By the way Camunda is also a part of this community ;-).

I really regret, that the models generated from Camunda visual tools are not directly usable in **dsntk** but it is like it is for now, maybe it will change in the future.

I hope I could help a little bit. I am closing this issue, but feel free to comment on it or reopen if anything else comes out.

Thanks for trying **dsntk**!
